### ISSUE TITLE
Improve model-based validations

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/azmet-qaqc#15]
Model diagnostics for the current "seasonal naive" model for solar radiation show autocorrelation and non-normal (leptokurtic) residuals.  See if this can be improved by maybe figuring out how to use ARIMA models with `fable`

**Comment by jeremylweiss** [comment]
With solar radiation, I think a theoretical model that calculates values based on latitude and day-of-year for a clear day (no clouds) would be the best first step. For QA/QC of station solar radiation values, our biggest concerns are dust/mud/bird crap/etc. partially obscuring the sensor and artificially lowering values on clear days, as well as sensor drift between calibration visits (typically every quarter). Being able to compare clear-day values between the theoretical model and station measurements would be valuable. Perhaps plotting a time series of such on the 'AZMet QA/QC dashboard' would be good?

**Comment by Aariq** [comment]
"Seasonal naive" is equivalent to ARIMA(0,0,0)(0,1,0)[365] (i.e. an ARIMA with no auto-regressive component, only a seasonal component). Seasonal naive seems to be as good or better that what the auto ARIMA selects for temperature and solar radiation.  Auto ARIMA also suggests something slightly different for different stations, so maybe seasonal naive is a good one-size-fits-all model to start with.  Although, I'm surprised that an auto-regressive component doesn't seem to improve the model (if it was hot yesterday, it should be hot today, right?).

**Comment by Aariq** [comment]
Exploring using GAMs instead of ARIMA: https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/

**Comment by Aariq** [comment]
Plenty of options with GAMs to fit the data better, but seems like GAMs are bad at forecasting.
