### ISSUE TITLE
Add QA for additional variables

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/azmet-qaqc#16]
Start with mean temperature and precipitation, then expand to the rest.

**Comment by jeremylweiss** [comment]
Internal consistency checks from 'NWS (1994) TSP 88-21-R2':
- if 'temp_airC' < 'dwpt', then FLAG (hourly)
- if 'temp_air_meanC' < 'dwpt_mean', then FLAG (daily)
- if 'temp_air_minC' > 'temp_air_meanC' > 'temp_air_maxC', then FLAG (daily)
- if 'wind_spd_mps' > 'wind_spd_max_mps', then FLAG (hourly)
- if 'wind_spd_mean_mps' > 'wind_spd_max_mps', then FLAG (daily)

**Comment by jeremylweiss** [comment]
Temporal consistency checks from 'NWS (1994) TSP 88-21-R2':
- if 'temp_airC' hourly delta > 19.4 C (35 F) per hour, then FLAG (hourly)
- if 'relative_humidity' hourly delta > 50 % per hour, then FLAG (hourly)
- if 'wind_spd_mps' hourly delta > 10.3 mps, then FLAG (hourly)

**Comment by jeremylweiss** [comment]
Temporal consistency ('persistence') checks:
- if 'sol_rad_total' < 1 for more than 14 hours, then ALERT (hourly)
- if 'wind_spd_mps' < 1 for more than 14 hours, then ALERT (hourly)
- if range of 'wind_vector_dir' < 1 for more than 14 hours, then ALERT (hourly)

**Comment by Aariq** [comment]
Thanks @jeremylweiss!  This is great.  I'm imagining a `pointblank` validation table with these checks, then a separate table / plots for forecast-based checks.

**Comment by Aariq** [comment]
> * if 'temp_airC' hourly delta > 19.4 C (35 F) per hour, then FLAG (hourly)
> * if 'relative_humidity' hourly delta > 50 % per hour, then FLAG (hourly)
> * if 'wind_spd_mps' hourly delta > 10.3 mps, then FLAG (hourly)

For this we could use historical data and look for deltas outside of some quantile
