### ISSUE TITLE
Determine which variables need QA

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/azmet-qaqc#3]
Some variables are derived and will need to be flagged or imputed if the variables they are derived from have errors. Therefore, only the primary variables need quality assurance. I can take a guess at which variables these are, but it would be useful to have a list of variables that are primary and ones that are derived.

**Comment by jeremylweiss** [comment]
[azmet-data-metadata.xlsx](https://github.com/cct-datascience/azmet-qaqc/files/9883665/azmet-data-metadata.xlsx)
OK, I just finished putting this spreadsheet together (which I've been wanting to do for awhile...). Hourly variables on the first sheet, daily on the second. Sorting on the 'type' column should answer this question.

**Comment by jeremylweiss** [comment]
An update to 'azmet-data-metadata.xlsx . . . 'actual vapor pressure' and 'vapor pressure deficit' are derived variables. Updated spreadsheet coming soon . . .

**Comment by jeremylweiss** [comment]
Please replace previous spreadsheet version with this one: 
[azmet-data-metadata.xlsx](https://github.com/cct-datascience/azmet-qaqc/files/9963897/azmet-data-metadata.xlsx)
